services:
  ow-roll:
    image: ow-roll:latest
    container_name: ow-roll
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
    restart: unless-stopped